# Generated by Django 4.1 on 2022-08-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vuz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('count_views', models.IntegerField()),
                ('count_guests', models.IntegerField()),
                ('VK', models.TextField()),
                ('VK_Subs', models.IntegerField()),
                ('VK_Video', models.IntegerField()),
                ('YT', models.TextField()),
                ('YT_Subs', models.IntegerField()),
                ('YT_Views', models.IntegerField()),
                ('TG', models.TextField()),
                ('TG_Subs', models.IntegerField()),
            ],
        ),
    ]
