# Generated by Django 4.1 on 2022-08-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wiki', models.TextField(null=True)),
                ('vk', models.TextField(null=True)),
                ('vk_subs', models.IntegerField(null=True)),
                ('vuzs', models.ManyToManyField(to='step1.vuz')),
            ],
        ),
    ]
